#!/usr/bin/env python3
"""
Voice tech radar — write docs/radar/YYYY-MM-DD.md.

Exit code is always 0 (ops-friendly weeklies). Combines a static watchlist of
sites with optional provider names scraped from this repo tree.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import re
import sys
from pathlib import Path
from typing import List, Set

REPO_ROOT = Path(__file__).resolve().parents[1]
RADAR_DIR = REPO_ROOT / "docs" / "radar"

# Static sites / docs worth a periodic human scan (no network required here).
STATIC_SITES = [
    ("xAI TTS", "https://docs.x.ai/developers/model-capabilities/audio/text-to-speech"),
    ("xAI Voice overview", "https://docs.x.ai/developers/model-capabilities/audio/voice"),
    ("ElevenLabs", "https://elevenlabs.io/docs"),
    ("Groq Audio", "https://console.groq.com/docs/speech-to-text"),
    ("Deepgram", "https://developers.deepgram.com/docs"),
    ("Resemble AI", "https://docs.resemble.ai"),
    ("Hume AI", "https://dev.hume.ai/docs"),
    ("OpenAI Audio", "https://platform.openai.com/docs/guides/text-to-speech"),
    ("Cartesia", "https://docs.cartesia.ai"),
    ("PlayHT / Supertonic ecosystem", "https://github.com/playht"),
    ("fal.ai models", "https://fal.ai/models"),
    ("OpenVoiceUI upstream", "https://github.com/MCERQUA/OpenVoiceUI"),
]

PROVIDER_GLOBS = [
    "tts_providers/*_provider.py",
    "providers/tts/*_provider.py",
    "providers/stt/*_provider.py",
    "providers/llm/*_provider.py",
]


def _extract_provider_names() -> List[str]:
    names: Set[str] = set()
    # File stems
    for pattern in PROVIDER_GLOBS:
        for path in REPO_ROOT.glob(pattern):
            stem = path.stem
            if stem in ("base_provider", "base", "__init__"):
                continue
            names.add(stem.replace("_provider", "").replace("_tts", ""))
    # Class names TheXProvider
    class_re = re.compile(r"class\s+(\w+(?:Provider|TTS|STT))\b")
    for pattern in PROVIDER_GLOBS:
        for path in REPO_ROOT.glob(pattern):
            try:
                text = path.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            for m in class_re.finditer(text):
                names.add(m.group(1))
    # Config keys
    cfg = REPO_ROOT / "tts_providers" / "providers_config.json"
    if cfg.is_file():
        try:
            import json

            data = json.loads(cfg.read_text(encoding="utf-8"))
            for key in (data.get("providers") or {}):
                names.add(str(key))
        except Exception:
            pass
    return sorted(names, key=str.lower)


def _render(date: str, providers: List[str]) -> str:
    lines = [
        f"# Voice tech radar — {date}",
        "",
        "_Auto-generated by `scripts/voice_tech_radar.py`. Source for humans;",
        "no live HTTP is required to produce this file._",
        "",
        "## Static watchlist",
        "",
    ]
    for title, url in STATIC_SITES:
        lines.append(f"- **{title}** — {url}")
    lines.extend(
        [
            "",
            "## Providers detected in this tree",
            "",
        ]
    )
    if providers:
        for p in providers:
            lines.append(f"- `{p}`")
    else:
        lines.append("_No provider modules matched; check repo layout._")
    lines.extend(
        [
            "",
            "## Operator checklist",
            "",
            "1. Skim xAI / ElevenLabs / Groq / Deepgram changelogs for API breaks.",
            "2. Confirm `XAI_API_KEY` / `GROQ_API_KEY` still valid (without committing secrets).",
            "3. Re-run `pytest -q tests/test_grok_tts_provider.py tests/test_registry.py` after upgrades.",
            "4. Note latency + pricing shifts in the weekly mermaid brief if material.",
            "",
            f"_Generated: {date}_",
            "",
        ]
    )
    return "\n".join(lines)


def main(argv: List[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--date",
        default=_dt.date.today().isoformat(),
        help="Radar date stamp (YYYY-MM-DD)",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print markdown instead of writing docs/radar/",
    )
    args = parser.parse_args(argv)

    try:
        providers = _extract_provider_names()
        body = _render(args.date, providers)
        if args.stdout:
            sys.stdout.write(body)
        else:
            RADAR_DIR.mkdir(parents=True, exist_ok=True)
            out = RADAR_DIR / f"{args.date}.md"
            out.write_text(body, encoding="utf-8")
            print(f"Wrote {out.relative_to(REPO_ROOT)} ({len(providers)} provider tokens)")
        return 0
    except Exception as exc:  # noqa: BLE001 — must always exit 0
        print(f"voice_tech_radar warning: {exc}", file=sys.stderr)
        try:
            RADAR_DIR.mkdir(parents=True, exist_ok=True)
            fallback = RADAR_DIR / f"{args.date}.md"
            fallback.write_text(
                f"# Voice tech radar — {args.date}\n\n_Generation partially failed: {exc}_\n",
                encoding="utf-8",
            )
        except Exception:
            pass
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
